// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealTimeButtonDemo.API.Data;

#nullable disable

namespace RealTimeButtonDemo.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250714121442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("RealTimeButtonDemo.Shared.Models.ButtonState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastClickedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastClickedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("ButtonStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#007bff",
                            IsActive = true,
                            LastClickedAt = new DateTime(2025, 7, 14, 12, 14, 42, 602, DateTimeKind.Utc).AddTicks(3485),
                            LastClickedBy = "system",
                            RoomId = "demo-room"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
